"""empty message

Revision ID: d1094ea38149
Revises: 
Create Date: 2021-12-02 00:09:01.296542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1094ea38149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirect_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('uri_type', sa.Enum('IDENTIFIER', 'URL', name='uritype'), nullable=True),
    sa.Column('redirect_type', sa.Enum('PERM', 'TEMP', name='redirecttype'), nullable=True),
    sa.Column('redirect_counter', sa.Integer(), nullable=True),
    sa.Column('activate_at', sa.DateTime(), nullable=True),
    sa.Column('deactivate_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redirect_urls')
    # ### end Alembic commands ###
